// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID        int32   `json:"id"`
	PostID    int32   `json:"PostId"`
	Author    string  `json:"Author"`
	Content   string  `json:"Content"`
	ParentID  *int32  `json:"ParentId,omitempty"`
	CreatedAt string  `json:"Created_At"`
	UpdatedAt *string `json:"Updated_At,omitempty"`
}

type Mutation struct {
}

type NewComment struct {
	PostID   int32  `json:"PostId"`
	Author   string `json:"Author"`
	Content  string `json:"Content"`
	ParentID *int32 `json:"ParentId,omitempty"`
}

type NewPost struct {
	Title       string  `json:"Title"`
	Content     string  `json:"Content"`
	Author      *string `json:"Author,omitempty"`
	PublishedAt *string `json:"Published_At,omitempty"`
	UpdatedAt   *string `json:"Updated_At,omitempty"`
}

type Post struct {
	ID              int32      `json:"id"`
	Title           string     `json:"Title"`
	Content         string     `json:"Content"`
	Author          string     `json:"Author"`
	PublishedAt     string     `json:"Published_At"`
	UpdatedAt       *string    `json:"Updated_At,omitempty"`
	Comments        []*Comment `json:"Comments"`
	CommentsAllowed bool       `json:"Comments_Allowed"`
}

type Query struct {
}

type Subscription struct {
}
